---
title: "Installing"
description: |
  Instructions for installing the required programs to use this template and
  create a new project from it.
order: 1
---

There are a few programs that are required to use this template to create a
project:

- [uv](https://docs.astral.sh/uv/): A tool for managing Python environments and
  running commands.
- [Python](https://www.python.org/): Required by Copier, the template tool.
- [Copier](https://copier.readthedocs.io/en/stable/): A template tool for making
  new projects in a standardised and structured way.

You can use uv to install these required programs, so [install
uv](https://docs.astral.sh/uv/getting-started/installation/) first. After you've
installed uv, you can easily install all the other programs (like Python) using:

```bash {filename="Terminal"}
uv tool install --with jinja2-time copier
```

To do the next steps, you also need to install:

- [Git](https://git-scm.com/): For version control and setting up Git to track
  the newly created project.
- [gh cli](https://cli.github.com/): For managing GitHub repositories and
  settings from the command line. There are some post-creation steps we've
  included that use gh to simplify setting up a GitHub repository for the
  project.
